spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dondon_dev
    username: dondon_dev_user
    password: dondon
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true